before_commands:
  - 'git submodule update --init --recursive'
filter:
    excluded_paths: [tests/*, build/*, specs/*]
tools:
    php_cs_fixer: true
    php_code_sniffer: true
    php_cpd: true
    php_hhvm: true
    php_mess_detector: true
    php_analyzer: true
    php_pdepend: true
    php_code_coverage: true

    sensiolabs_security_checker: true
